import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import { useContext, useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import SessionContext, {
  useSession,
  setSessionId,
} from "../components/session";

const Home: NextPage = ({ sessionInfo }) => {
  const sessionContext = useContext(SessionContext);

  setSessionId(sessionInfo);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button onClick={() => console.log(sessionContext)}>
          testa context
        </button>
        <button
          onClick={() => {
            setSessionId("session-atualizada-no-componente");
          }}
        >
          Muda a session
        </button>
        <Link href="/dashboard">
          <a>Navegar para página do dash</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;

export async function getServerSideProps(context: any, req, res) {
  const sessionInfo = "prop-passada-via-ssr";

  return { props: { sessionInfo } };
}
